//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyStopwatch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("754, 770")]
        public global::System.Drawing.Point TimeViewPoint {
            get {
                return ((global::System.Drawing.Point)(this["TimeViewPoint"]));
            }
            set {
                this["TimeViewPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140, 30")]
        public global::System.Drawing.Size TimeViewSize {
            get {
                return ((global::System.Drawing.Size)(this["TimeViewSize"]));
            }
            set {
                this["TimeViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1460, 240")]
        public global::System.Drawing.Point PriceViewPoint {
            get {
                return ((global::System.Drawing.Point)(this["PriceViewPoint"]));
            }
            set {
                this["PriceViewPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140, 740")]
        public global::System.Drawing.Size PriceViewSize {
            get {
                return ((global::System.Drawing.Size)(this["PriceViewSize"]));
            }
            set {
                this["PriceViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BootingArgs {
            get {
                return ((int)(this["BootingArgs"]));
            }
            set {
                this["BootingArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableTopMost {
            get {
                return ((bool)(this["EnableTopMost"]));
            }
            set {
                this["EnableTopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10:30\\r\\n20:30\\r\\n35:00")]
        public string TimeNodeCheckingList {
            get {
                return ((string)(this["TimeNodeCheckingList"]));
            }
            set {
                this["TimeNodeCheckingList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLogToFile {
            get {
                return ((bool)(this["EnableLogToFile"]));
            }
            set {
                this["EnableLogToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCheckTimeNode {
            get {
                return ((bool)(this["EnableCheckTimeNode"]));
            }
            set {
                this["EnableCheckTimeNode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableBossCountingAutoSlice {
            get {
                return ((bool)(this["EnableBossCountingAutoSlice"]));
            }
            set {
                this["EnableBossCountingAutoSlice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int BossCountingAutoSliceSeconds {
            get {
                return ((int)(this["BossCountingAutoSliceSeconds"]));
            }
            set {
                this["BossCountingAutoSliceSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 800")]
        public global::System.Drawing.Point BossCountingViewPoint {
            get {
                return ((global::System.Drawing.Point)(this["BossCountingViewPoint"]));
            }
            set {
                this["BossCountingViewPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Size BossCountingViewSize {
            get {
                return ((global::System.Drawing.Size)(this["BossCountingViewSize"]));
            }
            set {
                this["BossCountingViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugging {
            get {
                return ((bool)(this["EnableDebugging"]));
            }
            set {
                this["EnableDebugging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableBossCountingOneMode {
            get {
                return ((bool)(this["EnableBossCountingOneMode"]));
            }
            set {
                this["EnableBossCountingOneMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUsingScreenTopTime {
            get {
                return ((bool)(this["IsUsingScreenTopTime"]));
            }
            set {
                this["IsUsingScreenTopTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TimeViewPreset1Point {
            get {
                return ((global::System.Drawing.Point)(this["TimeViewPreset1Point"]));
            }
            set {
                this["TimeViewPreset1Point"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size TimeViewPreset1Size {
            get {
                return ((global::System.Drawing.Size)(this["TimeViewPreset1Size"]));
            }
            set {
                this["TimeViewPreset1Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TimeViewPreset2Point {
            get {
                return ((global::System.Drawing.Point)(this["TimeViewPreset2Point"]));
            }
            set {
                this["TimeViewPreset2Point"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size TimeViewPreset2Size {
            get {
                return ((global::System.Drawing.Size)(this["TimeViewPreset2Size"]));
            }
            set {
                this["TimeViewPreset2Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int TimeViewScanMiddleDelaySecond {
            get {
                return ((int)(this["TimeViewScanMiddleDelaySecond"]));
            }
            set {
                this["TimeViewScanMiddleDelaySecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableScreenTopTimeAutoLock {
            get {
                return ((bool)(this["EnableScreenTopTimeAutoLock"]));
            }
            set {
                this["EnableScreenTopTimeAutoLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crossfire,overwatch2,csgo")]
        public string ProcessListCSV {
            get {
                return ((string)(this["ProcessListCSV"]));
            }
            set {
                this["ProcessListCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("976, 216")]
        public global::System.Drawing.Point TimeViewTopPoint {
            get {
                return ((global::System.Drawing.Point)(this["TimeViewTopPoint"]));
            }
            set {
                this["TimeViewTopPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 60")]
        public global::System.Drawing.Size TimeViewTopSize {
            get {
                return ((global::System.Drawing.Size)(this["TimeViewTopSize"]));
            }
            set {
                this["TimeViewTopSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableTimeView2Blocks {
            get {
                return ((bool)(this["EnableTimeView2Blocks"]));
            }
            set {
                this["EnableTimeView2Blocks"] = value;
            }
        }
    }
}
